PROJECT_TARGET		= offline-finding
PROJECT_SOURCE_FILES	= uECC.c
PROJECT_CPP_SOURCE_FILES = main.cpp SHA_sha256.cpp uECC-handle.cpp

BLESSED_PATH := ../blessed

include $(BLESSED_PATH)/examples/Makefile.common
